import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const API='http://localhost:4000';
async function api(path,options){const r=await fetch(API+path,{headers:{'content-type':'application/json',...(options?.headers||{})},...options});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');return data;}

function App(){
 const [targets,setTargets]=useState([]),[selectedTarget,setSelectedTarget]=useState(null),[hierarchy,setHierarchy]=useState(null);
 const [name,setName]=useState(''),[subject,setSubject]=useState('DSA'),[topics,setTopics]=useState(['Arrays','Binary Search','Graphs','Dynamic Programming']);
 const [mode,setMode]=useState(null),[topicId,setTopicId]=useState(''),[session,setSession]=useState(null),[question,setQuestion]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null),[startedAt,setStartedAt]=useState(null);
 const loadTargets=async()=>{const d=await api('/api/targets');setTargets(d);};
 useEffect(()=>{loadTargets().catch(e=>setError(e.message));},[]);
 const selectTarget=async id=>{setError('');const d=await api(`/api/targets/${id}/concepts`);setSelectedTarget(d.target);setHierarchy(d);setMode(null);setSession(null);setQuestion(null);setResult(null);};
 const createTarget=async e=>{e.preventDefault();if(!name.trim()||!topics.filter(x=>x.trim()).length)return;setLoading(true);try{const d=await api('/api/targets',{method:'POST',body:JSON.stringify({name,subject,topics:topics.filter(x=>x.trim())})});await loadTargets();await selectTarget(d.target.id);setName('');}catch(e){setError(e.message)}finally{setLoading(false)}};
 const start=async chosenMode=>{setError('');setLoading(true);setResult(null);try{const d=await api('/api/revision/start',{method:'POST',body:JSON.stringify({targetId:selectedTarget.id,mode:chosenMode,topicConceptId:chosenMode==='topic'?Number(topicId):undefined})});setMode(chosenMode);setSession(d.session);setQuestion(d.question);setStartedAt(Date.now());}catch(e){setError(e.message)}finally{setLoading(false)}};
 const answer=async idx=>{if(!question||!session)return;setLoading(true);try{const d=await api(`/api/revision/${session.id}/answer`,{method:'POST',body:JSON.stringify({questionId:question.id,selectedIndex:idx,timeSeconds:Math.max(1,Math.round((Date.now()-startedAt)/1000))})});setResult({correct:d.correct,explanation:d.explanation,newMastery:d.newMastery});setSession(d.session);if(d.completed){setQuestion(null);const p=await api(`/api/targets/${selectedTarget.id}/concepts`);setHierarchy(p);}else{setQuestion(d.question);setStartedAt(Date.now());}}catch(e){setError(e.message)}finally{setLoading(false)}};
 const addTopic=()=>setTopics([...topics,'']);
 const updateTopic=(i,v)=>setTopics(topics.map((x,j)=>j===i?v:x));
 return <div className="app"><header><div><div className="eyebrow">ADAPTIVE LEARNING SYSTEM</div><h1>Adaptive Study Intelligence</h1><p>ML decides what to test. AI creates the question.</p></div><div className="status">● PostgreSQL + ML + Gemini</div></header>
 <main>
  <section className="card"><h2>Create a learning target</h2><form onSubmit={createTarget} className="form"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Target name e.g. DSA Placement Prep"/><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject"/><div className="topic-inputs">{topics.map((t,i)=><div className="topic-row" key={i}><input value={t} onChange={e=>updateTopic(i,e.target.value)} placeholder={`Topic ${i+1}`}/>{topics.length>1&&<button type="button" onClick={()=>setTopics(topics.filter((_,j)=>j!==i))}>×</button>}</div>)}</div><div className="actions"><button type="button" className="secondary" onClick={addTopic}>+ Add topic</button><button disabled={loading}>{loading?'Creating...':'Create target'}</button></div></form></section>
  <section className="card"><div className="section-head"><div><h2>Your targets</h2><span className="muted">Each newly selected topic starts with zero evidence.</span></div></div><div className="target-grid">{targets.map(t=><button key={t.id} className={`target ${selectedTarget?.id===t.id?'active':''}`} onClick={()=>selectTarget(t.id)}><strong>{t.name}</strong><span>{t.subject}</span><small>{t.topics?.length||0} topics</small></button>)}{!targets.length&&<div className="empty">Create your first learning target.</div>}</div></section>
  {hierarchy&&<><section className="card"><div className="section-head"><div><h2>{selectedTarget.name}</h2><span className="muted">Choose how the diagnostic should work.</span></div></div><div className="topic-grid">{hierarchy.topics.map(t=><div className="topic-card" key={t.id}><div className="topic-title"><strong>{t.name}</strong><span>{Math.round(t.mastery*100)}%</span></div><div className="bar"><i style={{width:`${Math.round(t.mastery*100)}%`}}/></div><div className="subchips">{t.subtopics.map(s=><span key={s.id}>{s.name}</span>)}</div></div>)}</div></section>
  <section className="card"><h2>Revision engine</h2><div className="modes"><div className={`mode ${mode==='complete'?'selected':''}`}><h3>Complete Revision</h3><p>Samples across the target and uses ML success probability to focus on weaker topics.</p><button onClick={()=>start('complete')} disabled={loading}>Start complete revision</button></div><div className={`mode ${mode==='topic'?'selected':''}`}><h3>Topic-Specific Revision</h3><p>Chooses among subtopics inside one topic and adapts difficulty to your state.</p><select value={topicId} onChange={e=>setTopicId(e.target.value)}><option value="">Select topic</option>{hierarchy.topics.map(t=><option key={t.id} value={t.concept_id}>{t.name}</option>)}</select><button onClick={()=>start('topic')} disabled={loading||!topicId}>Start topic revision</button></div></div></section>
  {session&&<section className="card quiz"><div className="quiz-meta"><span>{mode==='complete'?'COMPLETE REVISION':'TOPIC REVISION'}</span><span>Question {session.question_count}</span></div>{question?<><h2>{question.text}</h2><div className="options">{question.options.map((o,i)=><button key={i} onClick={()=>answer(i)} disabled={loading}>{o}</button>)}</div>{result&&<div className={`feedback ${result.correct?'good':'bad'}`}><strong>{result.correct?'Correct':'Not quite'}</strong><p>{result.explanation}</p><span>Updated mastery: {Math.round(result.newMastery*100)}%</span></div>}</>:<div className="complete-box"><h2>Diagnostic complete</h2><p>Your knowledge state has been updated. Start another mode to continue exploring weak areas.</p></div>}</section>}
  </>}
  {error&&<div className="error">{error}</div>}
 </main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
